version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${FLASK_PORT:-5000}:5000"
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - MODEL_NAME=${MODEL_NAME:-llama3.1}
    depends_on:
      - ollama
    networks:
      - chat-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chat-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chat-network

volumes:
  ollama_data:

networks:
  chat-network:
    driver: bridge